### ISSUE TITLE
Average Output by Ride Type Appears to be Incorrect

### ISSUE THREAD

**Issue by weissleb** [jasonlutterloh/metrics-peloton#20]
First off, this is very cool.  I found a potential bug with one of the charts, the AVERAGE OUTPUT BY RIDE TYPE.  I filtered down to a single ride, which has an output of 322 as can be seen in the top rides chart below.  However, the ride type chart shows this ride's average output as 179.  This is the *only* ride of this type.

![lutterloh-ride-type-bug](https://user-images.githubusercontent.com/7568883/107963233-e5ab5600-6f75-11eb-91d9-b257f283f053.png)

Unless I don't understand the ride type metric, it looks like a bug.

**Comment by jasonlutterloh** [comment]
Hey, sorry for the confusion. I may need a better explanation but in this context, "average output" refers to the average you maintain during the ride itself. So while your total may be 322, the average you maintained throughout the ride was 179 (Maybe you were at 100 during the warm up but closer to 300 during the climbs, that sort of thing). Then for multiple rides of the same type, I'm just averaging that metric. Hope that makes sense. Thanks for checking it out and providing the feedback! 

p.s. That Ministry of Sound ride is amazing. One of my hightest outputs ever.

**Comment by weissleb** [comment]
I see, you are using the Avg. Watts metric rather than Output.  Thanks for the clarification.

BTW, I was introduced to your site by a team member at work.  We have a pretty big intersection of Tableau enthusiasts and Peloton riders.  I hope you don't mind, but I [reproduced your charts](https://public.tableau.com/profile/brian.weissler#!/vizhome/PelotonLutterlohCharts/pelotonmetrics) as best I could using Tableau and the Peloton web data connector I created (of course I'll have to go back and fix this chart now that I understand it).

If you'd prefer I remove this workbook from Tableau Public, I will do so, since the creativity was yours (the description does link back to your site).  My goal is simply giving Tableau users easy access to their data without having to export it.

**Comment by jasonlutterloh** [comment]
Nah, I think that's awesome! I created this just as a way to track for myself and it turned into a fun project I thought I'd share. Glad you found some use out of it!

**Comment by weissleb** [comment]
Same story here.  Took on a little bit of a life of it's own 😅 , https://www.mypelotondata.com/home.  Be good, and stay safe.
