### ISSUE TITLE
Multiple rides in a day

### ISSUE THREAD

**Issue by markgould** [jasonlutterloh/metrics-peloton#4]
When riding multiple times in a day (I did five 60s the other day) I'm seeing the date repeated on the graph with different outputs. Maybe group by day and show the max or average?

I've attached my data but removed my user id (not sure that it really matters much)

Let me know if I can help in anyway, this is a great little project!

[data.txt](https://github.com/jasonlutterloh/metrics-peloton/files/4915291/data.txt)

**Comment by jasonlutterloh** [comment]
Ill take a look as soon as I can. Thanks for sending the data over too. That really helps with trying to test it out.

**Comment by jasonlutterloh** [comment]
@markgould First off, five 60s is crazy lol My hat's off to you. 
Second, I took a stab an option to hide/show same day rides. By default, I've left just the max output for the day.

Take a look and let me know what you think! Thanks again for the suggestion and data to help test!

**Comment by markgould** [comment]
Yeah, that looks great, thanks! It might be nice to view the graphs at a week/month level so you can see your best output over time, if that makes sense?
